### ISSUE TITLE
Deploying <'DAO Name'> to the Tezos Florence Testnet Network returns, "Something went wrong, please try again later." No further explanation given. 

### ISSUE THREAD

**Issue by jsocarras** [dOrgTech/homebase-app#199]

**Comment by namesty** [comment]
Hey! @jsocarras thanks for reaching out. We are working on more informative messages and will update our UI soon. However, to provide you with a faster solution, could you share your DAO creation parameters?

**Comment by jsocarras** [comment]
Hi, @namesty! Thanks for the reply! Here are my parameters: 

Token Address: KT1AFA2mwNUMNd4SsujE1YYp29vd8BZejyKW ID: 0 (I used the hDAO token by default; I'm unsure if this is problematic)
Voting Period: 5 minutes
Proposal Flush: 11 Minutes
Proposal Time: 12 Minutes
Required Stake to Propose: 1 OBJKT
Returned Stake after Proposal: 95%
Transfer Amounts: Min = 0.000001 XTZ, Max = 10 XTZ 
Quorum Threshold = 10%
Min = 1%
Max = 99% 
Quorum Change = 2%
Quorum Max Change = 10%
Administrator = <Tez Address>
Guardian = <Tez Address>

**Comment by namesty** [comment]
Hello again! @jsocarras I think this error was due to using token with address: KT1AFA2mwNUMNd4SsujE1YYp29vd8BZejyKW, because that token exists on mainnet, not on florencenet, where you attempted deployment. Nonetheless, you are right, we should have better handling for these kinds of details as they're very common.

While attempting deployment with your parameters I got #197 happening sometimes, so I'm looking into that. I'll leave this issue open for a couple of days in case you would like to add further information
