### ISSUE TITLE
Add max button on the deposit page

### ISSUE THREAD

**Issue by thenerdcat** [dOrgTech/homebase-app#288]
Add max button on the deposit page so users don't have to type out complete numbers.

**Comment by fjeffkirk** [comment]
Recommend also showing the users balance

**Comment by fjeffkirk** [comment]
The current live implementation is incorrect. for depositing The UI shows the "Use Max" button now when a user goes to deposit their DAO token, but when a user clicks that button it doesn't read the amount in their wallet. It reads the amount in the DAO. 

For example, right now I have 311 crDAO deposited in Homebase and I have 3 more crDAO I want to deposit. If I go to deposit my 3 crDAO tokens and hit the "Use Max" button, it will populate the amount deposited already and say 311 instead of 3. The withdraw modal correctly will pull the amount I have in the DAO.

**Comment by fjeffkirk** [comment]
Also, it would be helpful to actually see your balance like s
![Group 4](https://user-images.githubusercontent.com/38136491/184276711-781d0978-2f48-4d95-86d0-8bc35c258d97.png)
o
